export const REGISTER_USER_BEGIN = 'REGISTER_USER_BEGIN';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';

export const LOGIN_USER_BEGIN = 'LOGIN_USER_BEGIN';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';

export const UPDATE_USER_BEGIN = 'UPDATE_USER_BEGIN';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';

export const DELETE_USER_ACCOUNT_BEGIN = 'DELETE_USER_ACCOUNT_BEGIN';
export const DELETE_USER_ACCOUNT_SUCCESS = 'DELETE_USER_ACCOUNT_SUCCESS';
export const DELETE_USER_ACCOUNT_ERROR = 'DELETE_USER_ACCOUNT_ERROR';

export const LOGOUT_USER = 'LOGOUT_USER';

export const CREATE_BOARD_BEGIN = 'CREATE_BOARD_BEGIN';
export const CREATE_BOARD_SUCCESS = 'CREATE_BOARD_SUCCESS';
export const CREATE_BOARD_ERROR = 'CREATE_BOARD_ERROR';

export const GET_USER_BOARD_BEGIN = 'GET_USER_BOARD_BEGIN';
export const GET_USER_BOARD_SUCCESS = 'GET_USER_BOARD_SUCCESS';
export const GET_USER_BOARD_ERROR = 'GET_USER_BOARD_ERROR';

export const GET_USER_BOARD_COLUMN_SUCCESS = 'GET_USER_BOARD_COLUMN_SUCCESS';

export const DELETE_BOARD_BEGIN = 'DELETE_BOARD_BEGIN';
export const DELETE_BOARD_SUCCESS = 'DELETE_BOARD_SUCCESS';
export const DELETE_BOARD_ERROR = 'DELETE_BOARD_ERROR';

export const EDIT_BOARD_BEGIN = 'EDIT_BOARD_BEGIN';
export const EDIT_BOARD_SUCCESS = 'EDIT_BOARD_SUCCESS';
export const EDIT_BOARD_ERROR = 'EDIT_BOARD_ERROR';

export const GET_CURRENT_TASK = 'GET_CURRENT_TASK';
export const EDIT_SUBTASK = 'EDIT_SUBTASK';
export const MOVE_TASK = 'MOVE_TASK';

export const CREATE_COLUMN_TASK_BEGIN = 'CREATE_COLUMN_TASK_BEGIN';
export const CREATE_COLUMN_TASK_SUCCESS = 'CREATE_COLUMN_TASK_SUCCESS';
export const CREATE_COLUMN_TASK_ERROR = 'CREATE_COLUMN_TASK_ERROR';

export const DELETE_TASK_BEGIN = 'DELETE_TASK_BEGIN';
export const DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS';
export const DELETE_TASK_ERROR = 'DELETE_TASK_ERROR';

export const EDIT_TASK_BEGIN = 'EDIT_TASK_BEGIN';
export const EDIT_TASK_SUCCESS = 'EDIT_TASK_SUCCESS';
export const EDIT_TASK_ERROR = 'EDIT_TASK_ERROR';

export const DND_TASK_BEGIN = 'DND_TASK_BEGIN';
export const DND_TASK_SUCCESS = 'DND_TASK_SUCCESS';
export const DND_TASK_ERROR = 'DND_TASK_ERROR';

export const LOGIN_TEST_USER_BEGIN = 'LOGIN_TEST_USER_BEGIN';
export const LOGIN_TEST_USER_SUCCESS = 'LOGIN_TEST_USER_SUCCESS';
export const LOGIN_TEST_USER_ERROR = 'LOGIN_TEST_USER_ERROR';

export const DELETE_TASK_MODAL_TOGGLE = 'DELETE_TASK_MODAL_TOGGLE';
export const UPDATE_TASK_MODAL_TOGGLE = 'UPDATE_TASK_MODAL_TOGGLE';
export const SIDE_CREATE_MODAL_TOGGLE = 'SIDE_CREATE_MODAL_TOGGLE';
export const CREATE_NEW_BOARD_MODAL_TOGGLE = 'CREATE_NEW_BOARD_MODAL_TOGGLE';
export const DELETE_MODAL_TOGGLE = 'DELETE_MODAL_TOGGLE';
export const CLOSE_MODAL = 'CLOSE_MODAL';
export const EDIT_BOARD_MODAL_TOGGLE = 'EDIT_BOARD_MODAL_TOGGLE';
export const ADD_COLUMN_MODAL_TOGGLE = 'ADD_COLUMN_MODAL_TOGGLE';
export const ADD_TASK_MODAL_TOGGLE = 'ADD_TASK_MODAL_TOGGLE';
export const VIEW_TASK_MODAL_TOGGLE = 'VIEW_TASK_MODAL_TOGGLE';
